# This is a basic workflow to help you get started with Actions

name: windows

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
    #paths-ignore:
    #  - "**.md"
  pull_request:
    branches: [ develop ]
    #paths-ignore:
    #  - "**.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows:
    # The type of runner that the job will run on (ubuntu-latest)
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repository
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: print host infos
        shell: cmd
        run: echo %CD%

      - name: print wake help
        shell: cmd
        run: |
          %CD%\bin\windows\wake

      - name: rebuild modules
        shell: cmd
        run: |
          cd %CD%\scripts
          rebuildmods.bat

      - name: rebuild wake
        shell: cmd
        run: |
          cd %CD%\scripts
          rebuildwake.bat

      - name: rebuild wide
        shell: cmd
        run: |
          cd %CD%\scripts
          rebuildwide.bat

      - name: rebuild launcher
        shell: cmd
        run: |
          cd %CD%\scripts
          rebuildlauncher.bat

      - name: make docs
        shell: cmd
        run: |
          cd %CD%\scripts
          makedocs.bat